- name: Configure MySQL Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL 8 Version
  ansible.builtin.shell: dnf module disable mysql -y

- name: Install MySQL server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: installed

- name: Start MySQL server
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Load the file
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: out

- name: Print Out
  debug:
    msg: "{{out['content'] | b64decode}}"

#   | regex_findall('temporary password.*') |join('') | spilt('') | last